---
- hosts: yum
  tasks:
  - name: Update all install packages using YUM
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: remove packages not needed any more
    yum:
      autoremove: yes

  - name: Reboot packages when update
    reboot:
    when: yum_update_status.changed

- hosts: apt
  become: true
  tasks:
   - name: Update all installed packages using apt
     apt:
       name: '*'
       state: latest
       update_cache: yes
       only_upgrade: yes
     register: apt_update_status

   - name: remove packages not needed anymore
     apt:
       autoremove: yes

   - name: Reboot packages when update
     reboot:
     when: apt_update_status.changed
